// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || '';

const isMissing = !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY;

if (isMissing) {
  console.warn('⚠️ Supabase environment variables not loaded. Running in demo mode without backend.');
}

// Create client with placeholder values if missing (will fail silently on API calls)
export const supabase: SupabaseClient<Database> = createClient<Database>(
  SUPABASE_URL || 'https://placeholder.supabase.co',
  SUPABASE_PUBLISHABLE_KEY || 'placeholder-key',
  {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: !isMissing,
      autoRefreshToken: !isMissing,
    }
  }
);

// Helper to check if Supabase is available
export const isSupabaseConfigured = !isMissing;